CONSUMER_KEY = "CHANGE ME"
CONSUMER_SECRET = "CHANGE ME"
OAUTH_TOKEN = "CHANGE ME"
OAUTH_TOKEN_SECRET = "CHANGE ME"
INSTAPARSER_API_KEY = "CHANGE ME"
MONGO_AUTHENTICATION = 0
MONGO_USERNAME = "CHANGE ME"
MONGO_PASSWORD = "CHANGE ME"
